### PR TITLE
Add missing includes to 3.4 branch

### PR DESCRIPTION
**Pull request by dodopod**
godot3.4 branch won't build without 633e9ab and probably a few other changes

### CODE REVIEW

**Comment by Zylann** [comment]
It seems your PR has not been rebased, it carries a lot more commits than it should

**Comment by dodopod** [comment]
Oh, I merged instead of rebasing. Should i open another PR?

**Comment by Zylann** [comment]
You could rebase and then force-push on your branch, or make a new one

**Comment by Zylann** [comment]
Actually, I'm not sure if the 3.4 branch should get the new things present in master. That branch is a feature freeze, it should not get the stuff in master, which may have bugs also. Only bug fixes should be ported there.

**Comment by dodopod** [comment]
All right, I'll change it to only include the commits I need to avoid a compile error.

**Comment by dodopod** [comment]
I've rebased my fork with only the commits I need to build Godot with this module, and changed the title accordingly.

**Comment by Zylann** [comment]
Your commits still seem to contain the addition of `_b_set_node_name`

**Comment by dodopod** [comment]
Is this better?

**Comment by Zylann** [comment]
Yup, thanks!
Note: this will need to be ported to the godot4 banch if you need it as well

**Pull request merged**
