### PR TITLE
Added info in order to enable AO

### LINKED ISSUE #43: Add on docs to enable vertex color in order to enable AO
Hello folks!

Maybe I missed something, but I discovered by reading the source that we got a nice Ambient Occlusion if we just enable Vertex Color (Use as Albedo) on Material. When I first read the getting started, this wasn't obvious for me, so I think this should have a better emphasis on docs.

Thanks!

### PR DESCRIPTION
**Pull request by afonsolage**
Added on docs how to enable AO, as mentioned on #43

fixes #43

### CODE REVIEW

**Comment by Zylann** [comment]
I think you should precise that it's to be able to *see* the result of baked AO. Enabling vertex color does not *activate* AO, it's already there if the option is active (not exposed yet but one day it will). Also this kind of AO only exists for blocky voxels.

**Comment by tinmanjuggernaut** [comment]
The PR was done right.

@Zylann 
So you mean VT puts AO into the vertex color? So basically like blender's dirty vertex painting? And enabling vertex_color_use_as_albedo in the material mixes the vertex color with the albedo. Right?

In that case, @afonsolage, I'd write something like this:

```
Also, VoxelTerrain adds Ambient Occlusion to the vertex colors (blocky only). You can add this to your material by enabling the `Vertex Color/Use As Albedo` flag in your material.
```

Please also update Readme.md and change `Unlike a hightmap based terrain` to `Unlike a heightmap based terrain`.

These changes can then be squashed and force uploaded to your fork (see the doc I sent you). The PR will automatically update.
Thanks!

**Comment by Zylann** [comment]
> So you mean VT puts AO into the vertex color? So basically like blender's dirty vertex painting? And enabling vertex_color_use_as_albedo in the material mixes the vertex color with the albedo. Right?

Yes, that's correct :)

**Comment by tinmanjuggernaut** [comment]
Also you should put in " fixes #43 " in your initial post and it will automatically close that issue once the final PR is accepted.

**Comment by afonsolage** [comment]
Done! What about now?

**Comment by tinmanjuggernaut** [comment]
Good. Thanks for taking care of my typo. Finally, you'll want to squash your changes into one commit.  That doc I sent you shows you how, but basically you have three commits so you do this on your branch:
`git rebase -i HEAD~3`

Then keep the first commit and change the others to `fixup`. It will squash the extra two commits into the first and erase their commit messages (`squash` will keep the commit messages).
Then `git push --force origin update_material_docs` to overwrite your rebased log on your repository.

**Comment by afonsolage** [comment]
I had to change to `git rebase -i @~3` because i'm running on linux (base on [this answer](https://stackoverflow.com/a/47233396)). But anyway, This is my first PR, as you can see, so I'm learning a lot :+1:

**Pull request merged**
