### PR TITLE
[WIP] Godot 4.0 support based off master

### PR DESCRIPTION
**Pull request by tasgon**
Still a work in progress, doesn't compile yet and there are still quite a few things left to update.

I feel like this would be more appropriate as its own branch, but `godot4` seems to be already taken (and is quite a bit old compared to master, so GitHub's automated diffing tool doesn't take it well).

### CODE REVIEW

**Comment by slapin** [comment]
It would be nice to support 3.x version though as it is a lot of time to pass until Godot 4 is usable and a lot until it will pick up supported platforms back (i.e. GLES2) which will make Godot 3.x relevant for quite a while and having supported voxel module would be relevant too.

**Comment by Zylann** [comment]
https://github.com/Zylann/godot_voxel/tree/godot4 is up now. Compiles but runtime bugs may need to be fixed

**Comment by tasgon** [comment]
How did you deal with the meshoptimizer conflicts?

**Comment by Zylann** [comment]
Namespaced it

**Comment by Zylann** [comment]
I think I'll close this PR now because the port was done a while ago. Can still be accessed through the Closed PRs.

**Pull request closed without merging**
