### PR TITLE
missing lib?

### PR DESCRIPTION
**Pull request by El13B**
Included header file for the Dynamic memory management lib to define unique_ptr and shared_ptr.

### CODE REVIEW

**Comment by Zylann** [comment]
As discussed on Discord, this may be due to a recent version of GCC where internal headers had some dependencies removed.
Thanks!

**Comment by SneaK1ng** [comment]
> As discussed on Discord, this may be due to a recent version of GCC where internal headers had some dependencies removed. Thanks!

This discord link(https://discord.gg/pvgQvPDS) looks like invalid. Can you create a new one?

**Comment by Zylann** [comment]
Where did you get this link? It's not the same as the one in the readme

**Comment by SneaK1ng** [comment]
> Where did you get this link? It's not the same as the one in the readme

My fault:)

**Pull request merged**
