### PR TITLE
Add macOS x86_64 checks

### PR DESCRIPTION
**Pull request by DeeJayLSP**
As it says

### CODE REVIEW

**Comment by DeeJayLSP** [comment]
Mistake fixed

**Comment by DeeJayLSP** [comment]
Had forgot to add the Vulkan SDK install. I hope this is good now.

**Comment by Zylann** [comment]
Hmmm I restarted jobs after merging #534 but they dont seem to pickup the fix. Maybe you need to rebase?

**Comment by DeeJayLSP** [comment]
Changed the commit name

**Comment by DeeJayLSP** [comment]
I have a build log with everything that can fall into werror, will be taking a look.

**Comment by DeeJayLSP** [comment]
Fuzzer failing because no space left. Wow.

**Pull request merged**
